import pandas as pd

def load_kecamatan_data():
    data = [
    {"Kota": "Surabaya", "Kecamatan": "Karang Pilang", "Kepadatan": 8041},
    {"Kota": "Surabaya", "Kecamatan": "Jambangan", "Kepadatan": 13222},
    {"Kota": "Surabaya", "Kecamatan": "Gayungan", "Kepadatan": 7444},
    {"Kota": "Surabaya", "Kecamatan": "Wonocolo", "Kepadatan": 12256},
    {"Kota": "Surabaya", "Kecamatan": "Tenggilis Mejoyo", "Kepadatan": 10143},
    {"Kota": "Surabaya", "Kecamatan": "Gunung Anyar", "Kepadatan": 6142},
    {"Kota": "Surabaya", "Kecamatan": "Rungkut", "Kepadatan": 5397},
    {"Kota": "Surabaya", "Kecamatan": "Sukolilo", "Kepadatan": 3845},
    {"Kota": "Surabaya", "Kecamatan": "Mulyorejo", "Kepadatan": 5079},
    {"Kota": "Surabaya", "Kecamatan": "Gubeng", "Kepadatan": 16757},
    {"Kota": "Surabaya", "Kecamatan": "Wonokromo", "Kepadatan": 18591},
    {"Kota": "Surabaya", "Kecamatan": "Dukuh Pakis", "Kepadatan": 5784},
    {"Kota": "Surabaya", "Kecamatan": "Wiyung", "Kepadatan": 6179},
    {"Kota": "Surabaya", "Kecamatan": "Lakarsantri", "Kepadatan": 3440},
    {"Kota": "Surabaya", "Kecamatan": "Sambikerep", "Kepadatan": 4023},
    {"Kota": "Surabaya", "Kecamatan": "Tandes", "Kepadatan": 9234},
    {"Kota": "Surabaya", "Kecamatan": "Suko Manunggal", "Kepadatan": 11237},
    {"Kota": "Surabaya", "Kecamatan": "Sawahan", "Kepadatan": 27648},
    {"Kota": "Surabaya", "Kecamatan": "Tegalsari", "Kepadatan": 22624},
    {"Kota": "Surabaya", "Kecamatan": "Genteng", "Kepadatan": 14339},
    {"Kota": "Surabaya", "Kecamatan": "Tambaksari", "Kepadatan": 25309},
    {"Kota": "Surabaya", "Kecamatan": "Kenjeran", "Kepadatan": 21774},
    {"Kota": "Surabaya", "Kecamatan": "Bulak", "Kepadatan": 7667},
    {"Kota": "Surabaya", "Kecamatan": "Simokerto", "Kepadatan": 35271},
    {"Kota": "Surabaya", "Kecamatan": "Semampir", "Kepadatan": 20254},
    {"Kota": "Surabaya", "Kecamatan": "Pabean Cantian", "Kepadatan": 13491},
    {"Kota": "Surabaya", "Kecamatan": "Bubutan", "Kepadatan": 24860},
    {"Kota": "Surabaya", "Kecamatan": "Krembangan", "Kepadatan": 13357},
    {"Kota": "Surabaya", "Kecamatan": "Asemrowo", "Kepadatan": 3245},
    {"Kota": "Surabaya", "Kecamatan": "Benowo", "Kepadatan": 2813},
    {"Kota": "Surabaya", "Kecamatan": "Pakal", "Kepadatan": 3474},
    {"Kota": "Semarang", "Kecamatan": "Mijen", "Kepadatan": 1591},
    {"Kota": "Semarang", "Kecamatan": "Gunung Pati", "Kepadatan": 1729},
    {"Kota": "Semarang", "Kecamatan": "Banyumanik", "Kepadatan": 4823},
    {"Kota": "Semarang", "Kecamatan": "Gajah Mungkur", "Kepadatan": 6031},
    {"Kota": "Semarang", "Kecamatan": "Semarang Selatan", "Kepadatan": 10457},
    {"Kota": "Semarang", "Kecamatan": "Candisari", "Kepadatan": 11820},
    {"Kota": "Semarang", "Kecamatan": "Tembalang", "Kepadatan": 5038},
    {"Kota": "Semarang", "Kecamatan": "Pedurungan", "Kepadatan": 9310},
    {"Kota": "Semarang", "Kecamatan": "Genuk", "Kepadatan": 5099},
    {"Kota": "Semarang", "Kecamatan": "Gayamsari", "Kepadatan": 11320},
    {"Kota": "Semarang", "Kecamatan": "Semarang Timur", "Kepadatan": 12262},
    {"Kota": "Semarang", "Kecamatan": "Semarang Utara", "Kepadatan": 10348},
    {"Kota": "Semarang", "Kecamatan": "Semarang Tengah", "Kepadatan": 10672},
    {"Kota": "Semarang", "Kecamatan": "Semarang Barat", "Kepadatan": 6889},
    {"Kota": "Semarang", "Kecamatan": "Tugu", "Kepadatan": 1202},
    {"Kota": "Semarang", "Kecamatan": "Ngaliyan", "Kepadatan": 3385},
    {"Kota": "Jakarta", "Kecamatan": "Jagakarsa", "Kepadatan": 15416},
    {"Kota": "Jakarta", "Kecamatan": "Pasar Minggu", "Kepadatan": 14028},
    {"Kota": "Jakarta", "Kecamatan": "Cilandak", "Kepadatan": 11101},
    {"Kota": "Jakarta", "Kecamatan": "Pesanggrahan", "Kepadatan": 19348},
    {"Kota": "Jakarta", "Kecamatan": "Kebayoran Lama", "Kepadatan": 18453},
    {"Kota": "Jakarta", "Kecamatan": "Kebayoran Baru", "Kepadatan": 10794},
    {"Kota": "Jakarta", "Kecamatan": "Mampang Prapatan", "Kepadatan": 18805},
    {"Kota": "Jakarta", "Kecamatan": "Pancoran", "Kepadatan": 19764},
    {"Kota": "Jakarta", "Kecamatan": "Tebet", "Kepadatan": 24498},
    {"Kota": "Jakarta", "Kecamatan": "Setiabudi", "Kepadatan": 12138},
    {"Kota": "Jakarta", "Kecamatan": "Kembangan", "Kepadatan": 12972},
    {"Kota": "Jakarta", "Kecamatan": "Kebon Jeruk", "Kepadatan": 20502},
    {"Kota": "Jakarta", "Kecamatan": "Palmerah", "Kepadatan": 31287},
    {"Kota": "Jakarta", "Kecamatan": "Grogol Petamburan", "Kepadatan": 23900},
    {"Kota": "Jakarta", "Kecamatan": "Tambora", "Kepadatan": 49972},
    {"Kota": "Jakarta", "Kecamatan": "Taman Sari", "Kepadatan": 16537},
    {"Kota": "Jakarta", "Kecamatan": "Cengkareng", "Kepadatan": 22234},
    {"Kota": "Jakarta", "Kecamatan": "Kalideres", "Kepadatan": 15361},
    {"Kota": "Jakarta", "Kecamatan": "Tanah Abang", "Kepadatan": 18654},
    {"Kota": "Jakarta", "Kecamatan": "Gambir", "Kepadatan": 12639},
    {"Kota": "Jakarta", "Kecamatan": "Kemayoran", "Kepadatan": 35303},
    {"Kota": "Jakarta", "Kecamatan": "Menteng", "Kepadatan": 13487},
    {"Kota": "Jakarta", "Kecamatan": "Sawah Besar", "Kepadatan": 20506},
    {"Kota": "Jakarta", "Kecamatan": "Cempaka Putih", "Kepadatan": 41478},
    {"Kota": "Jakarta", "Kecamatan": "Senen", "Kepadatan": 29480},
    {"Kota": "Jakarta", "Kecamatan": "Johar Baru", "Kepadatan": 29955},
    {"Kota": "Jakarta", "Kecamatan": "Penjaringan", "Kepadatan": 6927},
    {"Kota": "Jakarta", "Kecamatan": "Pademangan", "Kepadatan": 13758},
    {"Kota": "Jakarta", "Kecamatan": "Tanjung Priok", "Kepadatan": 17916},
    {"Kota": "Jakarta", "Kecamatan": "Koja", "Kepadatan": 27566},
    {"Kota": "Jakarta", "Kecamatan": "Kelapa Gading", "Kepadatan": 9249},
    {"Kota": "Jakarta", "Kecamatan": "Cilincing", "Kepadatan": 10991},
    {"Kota": "Jakarta", "Kecamatan": "Pasar Rebo", "Kepadatan": 17364},
    {"Kota": "Jakarta", "Kecamatan": "Ciracas", "Kepadatan": 18863},
    {"Kota": "Jakarta", "Kecamatan": "Cipayung", "Kepadatan": 10398},
    {"Kota": "Jakarta", "Kecamatan": "Makasar", "Kepadatan": 9611},
    {"Kota": "Jakarta", "Kecamatan": "Kramat Jati", "Kepadatan": 23175},
    {"Kota": "Jakarta", "Kecamatan": "Jatinegara", "Kepadatan": 29901},
    {"Kota": "Jakarta", "Kecamatan": "Duren Sawit", "Kepadatan": 18421},
    {"Kota": "Jakarta", "Kecamatan": "Cakung", "Kepadatan": 13381},
    {"Kota": "Jakarta", "Kecamatan": "Pulo Gadung", "Kepadatan": 18119},
    {"Kota": "Jakarta", "Kecamatan": "Matraman", "Kepadatan": 36017},
]
    return pd.DataFrame(data)
